package es.cesur.progprojectpok.clases;

public enum Estado {
    CONGELADO, PARALIZADO, QUEMADO, CONFUNDIDO, DORMIDO, ENVENENADO,
    INTOXICADO, SOMNOLIENTO, HELADO, MALDITO, ENAMORADO, DRENADORAS,
    APRESADO, HUIDA_IMPOSIBLE, CUENTA_ATRAS, AMEDRENTADO, CENTRO_ATENCION, FATIGA, POKERUS, DEBILITADO, SALUDABLE
}
