package es.cesur.progprojectpok.clases;

public enum Tipos {
    NORMAL, FUEGO, AGUA, PLANTA, ELECTRICO, HIELO, LUCHA, VENENO, TIERRA, VOLADOR, PSÍQUICO, BICHO, ROCA, FANTASMA, DRAGÓN, SINIESTRO, ACERO
}
